### ISSUE TITLE
Parser Error Message: An error occurred creating the configuration section handler for common/logging: parent configuration sections are not allowed

### ISSUE THREAD

**Issue by vic10us** [net-commons/common-logging#115] opened 2016-01-08 18:35 UTC
Problem when using Web.config

This config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>

  <configSections>
    <sectionGroup name="common" >
      <section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging" />
    </sectionGroup>
  </configSections>
  <common>
    <logging>
      <factoryAdapter type="Common.Logging.Log4Net.Log4NetLoggerFactoryAdapter, Common.Logging.Log4Net1213">
        <arg key="configType" value="FILE-WATCH" />
        <arg key="configFile" value="~/log4net.config" />
      </factoryAdapter>
    </logging>
  </common>
...
</configuration>
```

results in the following error:

```
Configuration Error

Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately. 

Parser Error Message: An error occurred creating the configuration section handler for common/logging: parent configuration sections are not allowed

Source Error: 


Line 11:   </configSections>
Line 12:   <common>
Line 13:     <logging>
Line 14:       <factoryAdapter type="Common.Logging.Log4Net.Log4NetLoggerFactoryAdapter, Common.Logging.Log4Net1213">
Line 15:         <arg key="configType" value="FILE-WATCH" />
```

Please help :sos:

**Comment by vic10us** [comment] 2016-01-13 15:59
Nothing? :disappointed:

**Comment by sbohlen** [comment] 2016-01-13 16:07
Sorry for the delay, I am traveling on business; let me try to take a look @ this for you tonight when I get to a hotel room and have some down-time....

**Comment by vic10us** [comment] 2016-01-13 16:07
Thank you very much! :)

**Comment by sbohlen** [comment] 2016-04-22 10:06
This looks correct (see https://github.com/net-commons/common-logging/blob/master/examples/SimpleWebApplication/web.config).  I'm unable to repro your error; can you validate/verify that this problem persists --?

**Comment by cumminsjp** [comment] 2016-05-23 20:16
I am also getting this error with my WebAPI (.NET 4.5.1) and I'm just using a TraceLoggerFactoryAdapter.  I haven't worked out what the cause is.  For me, I get it when I click the WebAPI help (or if I load that url directly).  But if I just load the site, I don't get errors on the startup.  But when I click API, I do get the error:

![image](https://cloud.githubusercontent.com/assets/5941336/15483229/9cf672a4-2101-11e6-9923-2f7caed7eacc.png)


On startup, everything looks good.  I get my initial logging statement:
![image](https://cloud.githubusercontent.com/assets/5941336/15483246/b849a38c-2101-11e6-8e6a-457ab8efce08.png)


And the site loads:
![image](https://cloud.githubusercontent.com/assets/5941336/15482929/47c88d0e-2100-11e6-9c50-874626d729d7.png)

Click the API link, and the exception is thrown from Common.Logging.ConfigurationSectionHandler.Create

Sure enough, parent is NOT null:
![image](https://cloud.githubusercontent.com/assets/5941336/15483160/48e57cb4-2101-11e6-926c-0d37b025d8cc.png)

**Comment by sbohlen** [comment] 2016-05-23 20:53
@cumminsjp 

Any chance you could provide a (minimal) repro for me (either in a public git repo somewhere or else by directly emailing me a sample if it contains code you don't want to share publicly for any reason) --?  I'm happy to try to puzzle out for you what's wrong here (esp. since it seems that,while not ubiquitous, this error also isn't _entirely_ unique to just one situation), but without a repro case I can actually examine/run/inspect myself, I'm not (immediately) able to provide much additional assistance here.

Since the web.config provided by the OP seems otherwise valid, I'm assuming that the issue is something more complex at its root that is somehow surfacing itself as an error in the config file.  Your own report of it "working" once and then failing a second time would seem to bear this out -- obviously if it really was a problem with the config syntax/parsing it wouldn't even work the first time.

Alternately, if you can't share your project or else provide a suitable repro case for me to examine, the only other suggestion I can offer would be for you to pull down the `Common.Logging` source, add it your project, and debug directly into `Common.Logging` during the exception in order to try to gather more info for me that I could potentially use to further assist you (this is what I'd do if/when you provide me a repro sample anyway).

Can you (somehow) provide a minimalist repro case for me --?

**Comment by cumminsjp** [comment] 2016-05-24 13:41
So....when I tried to create a small repro-repo with a matching set of packages, I couldn't reproduce.  Eventually, I ended up clearing out the DevelopmentServerPort and IISUrl out of the csproj and letting Visual Studio pick a new one. And that resolved it.  

I must have something spun up on that port, but I haven't been able to track it down.

**Comment by sbohlen** [comment] 2016-05-24 14:01
OK, great -- my kind of issue, the one's that solve themselves:)  Happy you were able to get past it.

I'll close this issue for now and we can re-open it if necessary should more info become available or the situation changes.

**Closed by sbohlen** 2016-05-24 14:01 UTC
Labels: question
