### ISSUE TITLE
Add Support for Serilog

### ISSUE THREAD

**Issue by aaronmell** [net-commons/common-logging#121] opened 2016-05-31 22:45 UTC
I'd like to see support for Serilog as part of Common.Logging. It might make for an interesting side project, and something that isn't too much effort to implement.

What version(s) need to be supported? Is it okay if the implementation only targets the current version 1.5?

Anything specific that someone implementing the new logger would need to be mindful of?

**Comment by sbohlen** [comment] 2016-06-01 10:35
Wow -- how's that for serendipity???  There were two new logging targets for which I was hoping to add support leading up to the 3.4 (next) launch: one was ETW, which we've just now pushed to MASTER in its initial ALPHA state this past weekend, and the second was `Serilog`.

About a month ago I'd done some initial research leading up to that effort, but no code has yet been written.  If you'd want to FORK the repo and take a shot at an initial implementation of this, it would be much appreciated.  TBH, its always better when the effort is driven by someone who is an actual _user_ of the target logging framework because in that capacity you're more likely to be aware of the nuances of the features exposed by the logger (and thus arrive at a richer implementation for `Common.Logging`).  I've never used `Serilog` myself and so much more ramp-up would be required for me to be the best candidate to author support for it from scratch.

In re: what versions need to be supported, there's no requirement for support of any specific version of Serilog, although the objective would ideally be to target the version(s) that satisfy the following conditions:
1. Most broadly-adopted today
2. Current/latest version

If `Serilog` 1.5 meets both those criteria, then IMO supporting only 1.5 would be fine.  Either way, support for 1.5 (latest?) certainly seems a logical starting point for a first-pass and we can consider extending support to other earlier versions on an as-needed basis.  FWIW, if you look @ how support for multiple versions of e.g., Log4Net, NLog was accomplished you can see that in most cases its mostly about creating a new CSPROJ, changing the references to reflect the proper logger version, and linking to the existing .cs files from the other version (so in most cases little if any actual code changes tend to be required to support multiple versions of the same canonical logging target).

The best way to consider guidance re: how to get started is probably to review the recently-committed implementation of [the Common.Logging.ETWLogger project](https://github.com/net-commons/common-logging/tree/master/src/Common.Logging.ETWLogger).  This project contains one each of everything you'd (probably) have to consider to support `Serilog`:
- A class that derives from `AbstractLogger` that overrides `.WriteInternal(...)` to do the actual logging
- A class that derives from `AbstractCachingLoggerFactoryAdapter` that overrides `.CreateLogger(...)` to build and retrieve the actual logger instance and offers a ctor that takes a `NameValueCollection` instance that is hydrated from the default infrastructure that reads values from e.g., `app.config`, `web.config` files

If you find that you need more guidance than this, just return to this thread and post any Qs you might have; we're always happy to assist contributors to the project~!

One quick Q: as the ideal goal had been to include `Serilog` support in an upcoming 3.4 release of `Common.Logging` this effort now (potentially) blocks that release.  Do you have any approximate time-line for when you would expect to be able to get to this effort?  If its (somewhat) near-term then I think we're happy to wait on the 3.4 release for you to make significant progress on this, but if your time-horizon is longer then we might want to consider releasing `Common.Logging` 3.4 with ETW support soon and wait to add `Serilog` support in a future 3.5 release ... thoughts on this are welcome!

**Comment by aaronmell** [comment] 2016-06-01 13:57
I was thinking about working on it towards the end of the week, maybe over the weekend some and into next week assuming nothing comes up. On the surface it doesn't seem like too much work, but I guess I won't know exactly until I dig into it.

**Comment by sbohlen** [comment] 2016-06-01 15:35
Ha -- yes, not seeking an estimate for a scope you can't quantify as much as seeking general intent :)  That sounds perfectly fine to me -- let us know if you hit any blockers and we'll try to assist.  Looking forward to the contribution and thanks again!

**Comment by aaronmell** [comment] 2016-06-04 21:01
I've got a very rough version passing a few tests and I have a question about an implementation detail. Serilog doesn't have any sort of namespaced logging. It does offer the ability to enrich a log statement with additional meta data, so I think I am going to add the namespacing that way.

**Comment by sbohlen** [comment] 2016-06-04 22:00
From what I understand, I'd agree that seems a reasonable approach as a first-pass.

**Comment by aaronmell** [comment] 2016-06-07 02:48
I'm ready for a code review. I tried to keep things inside the serilog assemblies as best as possible. However, I did have to modify a few things to make it fit correctly. If you can think of a better approach, I can make some corrections.

**Comment by sbohlen** [comment] 2016-06-07 12:44
Thanks for this -- I'll take a look ASAP.  Unfortunately I'm traveling this week on business, but will try to dig into this during the next few days while I'm still away.  Based on my schedule, I may not be able to give this a thorough once-over until the coming weekend, but I'll try to review it sooner if at all possible.

**Comment by sbohlen** [comment] 2016-06-18 11:47
I've merged [the PR](https://github.com/net-commons/common-logging/pull/123).  Given your commit commit identifying this as a "first pass", can you let me know if there are other features you'd (still) want to add to your implementation before we'd consider it "ready to be released"?

**Comment by sbohlen** [comment] 2016-06-18 17:05
Also, I've just become aware that [this test fixture](https://github.com/net-commons/common-logging/blob/master/test/Common.Logging.Serilog1514.Tests/Logger/Serilog/SerilogTests.cs#L31) has two failing tests from the base-class; I've (temporarily) placed an `[Ignore]` attribute on the fixture so the CI build won't be in a **RED** condition.  It will probably be at least a few days before I'm able to dig into this in more detail to understand why this might be the case, so if possible it would be very helpful if you'd be willing to take a look in the meantime.

Obviously before this is released we'll want to adjust the implementation such that the failing tests pass, or else confirm with certainty that the failing tests are inappropriate to `Serilog` (e.g., the failures are proper and so the `Serilog` support in `Common.Logging` should be excepted from those specific tests) so that we can remove the `[Ignore]` from the fixture and still have the build **GREEN**.

Thanks again for the contribution!

**Comment by aaronmell** [comment] 2016-06-20 20:19
I think I got all of the features required for a first pass. I don't see anything obvious that is missing.

**Comment by aaronmell** [comment] 2016-06-20 20:24
Not exactly sure just from a glance at the build as to why its failing. The tests were green passing originally on my PR. Looks like some refactoring may have introduced the failures. If I get a chance the next couple of days, I'll try pulling latest and see if I can't tell whats gone wrong.

**Comment by sbohlen** [comment] 2016-06-20 20:33
Thanks; if they were (initially) passing for you then its quite likely some of my refactoring introduced the failure.  I (probably) won't be able to look @ this until the coming weekend so if you have a chance before then please let me know what you find.  Otherwise, I'll address it this coming weekend by comparing your PR to the current state of MASTER and using that as a guide to the issue.

**Comment by sbohlen** [comment] 2016-07-03 18:21
Just to close the loop on this, I finally had time this weekend to return to your PR and confirm that (on at least two sep. systems) the same two tests fail in your original PR as well (meaning it seems unrelated to any of the post-merge refactoring I'd done as we'd hypothesized).

I've since confirmed that this is b/c Serilog doesn't have the `[AllowPartiallyTrustedCallers]` attribute on its assembly.  The two failing tests attempt to create a logger instance and invoke it in a `PartialTrust` security context and this is incompatible with assemblies not flagged with the identified attribute.

I've adjusted the failing tests to invoke under the `FullTrust` context in https://github.com/net-commons/common-logging/commit/a411a1529df913ad6c49f62e6021b6de2302c8c8 and these tests are now properly passing so I'm formally closing this issue.

Thanks again for the PR!

**Closed by sbohlen** 2016-07-03 18:21 UTC
