### ISSUE TITLE
Could not install package 'Common.Logging.Core 3.3.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111',

### ISSUE THREAD

**Issue by philipogorman** [net-commons/common-logging#137] opened 2016-10-17 17:17 UTC
I tried to install on a PCL project and got the following error: 
Could not install package 'Common.Logging.Core 3.3.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111',

**Comment by philipogorman** [comment] 2016-10-17 20:30
I tried the beta and it worked  
<package id="Common.Logging.Core" version="3.4.0-Beta2" targetFramework="portable45-net45+win8+wpa81" />

**Comment by philipogorman** [comment] 2016-10-18 16:16
Actually - I can't get the portable package to install on a portable project:
Could not install package 'Common.Logging.Portable 3.4.0-Beta2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by AJF4** [comment] 2016-10-25 08:33
I'm seeing this too, with Latest prerelease 3.4.0-Beta2

**Comment by braingame26** [comment] 2017-07-25 21:22
Will support for this target be added?

**Comment by sbohlen** [comment] 2017-07-26 10:02
Hmmm...this is peculiar.  From my research [here](https://portablelibraryprofiles.stephencleary.com/) my understanding was that Profile111 is a _subset_ of Profile259 (111 is effectively 259 _minus_ 259's support for WP Silverlight 8.0).  Can you confirm this --?

If this is the case, then I'd have expected any project targeting Profile111 to 'accept' binaries packaged as targeting Profile259, since 259 is a _superset_ of 111.

If I'm right, then this is just the result of a NuGet behavior inconsistency.  If NuGet won't accept binaries for a profile that's a subset of the profile your project is actually targeting (can anyone confirm this is the expected behavior?) then we can resolve this ourselves by effectively taking the contents of our `portable-net45+win8+wpa81+wp8` folder and duplicating them into a `portable-net45+win8+wpa81` folder in the package.

Would you be willing to test the _binary_ compatibility of the RC2 bits with your Profile111 project by performing the following steps and then reporting your results?

1. install the `Common.Logging.Portable` package into somewhere _else_ on your filesystem independent of your project by e.g., `nuget.exe install Common.Logging.Portable -pre`

1. reference the binaries found in the `portable-net45+win8+wpa81+wp8` folder into your project manually via Visual Studio

1. determine whether it compiles/runs as expected

If YES, then we can solve this by just changing the packaging as I'd outlined above.  If not, then we would need to investigate why the binaries aren't compatible and determine the level of effort needed to make them so before we move to GA.

Thanks~!

**Comment by sbohlen** [comment] 2017-07-26 10:07
Also, in re-reading your comments, I want to confirm that you're using the latest pre-release (RC1) instead of the Beta-2 package (?)  Our expectation is that this _should work_ in the RC1 package, but it was definitely a packaging error we'd made in the Beta-2 package.  Can you confirm that you're using the RC1 package in your testings?

Thanks!

**Comment by philipogorman** [comment] 2017-07-26 17:51
@sbohlen confirmed the latest prerelease works! Thank you. When will it move to release, I want to take the beta off a lot of packages, thanks for your great work!

**Comment by sbohlen** [comment] 2017-07-26 18:08
Excellent news -- thanks for the quick response.  I'll close this issue as `RESOLVED` in `3.4-RC1`.

re: schedule for release, assuming no other negative feedback is received in the next few days, our plan is to move `3.4-RC1` to `3.4-GA` by the end of this month (JUL 31, 2017), so its literally just about any day now.

Thanks for your (continued) patience as we work to get our portable/packaging world in order!

**Closed by sbohlen** 2017-07-26 18:08 UTC
