### ISSUE TITLE
sectionResult is not assignable to Common.Logging.Configuration.LogSetting for Common.Logging.Portable

### ISSUE THREAD

**Issue by braingame26** [net-commons/common-logging#149] opened 2017-07-27 23:06 UTC
Hello,

I have a solution that contains both PCL and non-PCL projects. I've added the config sections below to my web.config.
```
<configSections>
    <sectionGroup name="common">
      <section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging" />
    </sectionGroup>
  </configSections>

  <common>
    <logging>
      <factoryAdapter type="Common.Logging.Simple.ConsoleOutLoggerFactoryAdapter, Common.Logging">
        <arg key="level" value="INFO" />
        <arg key="showLogName" value="true" />
        <arg key="showDateTime" value="true" />
        <arg key="dateTimeFormat" value="yyyy/MM/dd HH:mm:ss:fff" />
      </factoryAdapter>
    </logging>
  </common>
```
When I try running my application I get the following error.

>Type 'Common.Logging.Configuration.LogSetting, Common.Logging, Version=3.3.1.0, Culture=neutral, PublicKeyToken=af08829b84f0328e' of parameter 'sectionResult' is not assignable to target type 'Common.Logging.Configuration.LogSetting, Common.Logging.Portable, Version=3.3.1.0, Culture=neutral, PublicKeyToken=af08829b84f0328e'
Parameter name: sectionResult 

The output structure looks like this:
web.config
bin
&nbsp;&nbsp;&nbsp;&nbsp;PCL
&nbsp;&nbsp;&nbsp;&nbsp;Non-PCL
&nbsp;&nbsp;&nbsp;&nbsp;Common.Logging.dll
&nbsp;&nbsp;&nbsp;&nbsp;Common.Logging.Core.dll
&nbsp;&nbsp;&nbsp;&nbsp;Common.Logging.Portable.dll

The PCL references Common.Logging.Portable and the Non-PCL references Common.Logging.

What am I doing wrong?

**Comment by sbohlen** [comment] 2017-07-28 01:35
I'm not 100% certain that I'm properly understanding your use-case.  Can you elaborate on what you mean by

>The output structure looks like this:
>web.config
>bin
>PCL
>Non-PCL
>Common.Logging.dll
>Common.Logging.Core.dll
>Common.Logging.Portable.dll

Do you mean that's the structure of the various projects in your solution?  Or other?  It may be that you're attempting something that's either not supported or at a minimum intended to work but somehow not properly tested by us, but I can't tell for certain (yet).  As I _think_ I understand your situation, this _should_ be supported.  At a glance, your config file contents appear proper/correct, so I don't immediately think that's a factor.

If its difficult for you to describe your structure, would it perhaps be possible for you to create a mostly-empty solution (e.g., no code really necessary) but with the types of projects and their references to each other (and the relevant `Common.Logging` assemblies) that mimic your case and attach it as a ZIP file to this issue thread?  That might be the simplest way to convey the details of what you're trying to do (?)

Also, as a quick test can you temporarily update your references to the `3.4-RC2` pre-release package(s) and advise whether the issue is still present?  We're planning to release `3.4-GA` on either 7/31 or 8/1 (e..g, in 4-5 days) and so if updating to the latest solves the issue I'd (obviously) recommend that you just update to `3.4-GA` once its released.

Thanks!

**Comment by braingame26** [comment] 2017-07-28 03:32
Sorry, the title was misleading. The original title referenced a different issue that I worked around while I was in the middle of writing.

In my previous post where I show the output structure, I added some indentations to show what is under the bin folder, but the indentations didn't show up. I edited my previous post and now it looks good.

What happened was I tried having all my projects reference Common.Logging.Portable, but the error I ran into was it couldn't find the ConfigurationSectionHandler. I took a look at the Common.Logging.Portable dll and it wasn't there. I then just tried adding the Common.Logging dll to my bin folder, so it could find the ConfigurationSectionHandler. It found it, but then I ran into the error in my previous post.

I'll make a small project and send it to you tomorrow.

**Comment by sbohlen** [comment] 2017-07-28 10:12
@braingame26 

Thanks for the clarification -- after your indentations that makes more sense to me :)

We'll wait for your 'repro sample' project and then try to dig into this for you.  As mentioned, I _think_ what you're trying to do _should_ be supported, but its also certainly possible that you've uncovered a design flaw in our existing multi-targeting packaging strategy that we need to address ASAP.

Thanks!

**Comment by braingame26** [comment] 2017-07-28 14:00
[common.logging.tests.zip](https://github.com/net-commons/common-logging/files/1183238/common.logging.tests.zip)

Here's 2 sample solutions I made that demonstrates the problems I'm running into. Thanks!

**Comment by sbohlen** [comment] 2017-07-28 21:53
I've taken a look @ the sample projects (thanks for taking the time to create these, BTW, they are perfect for conveying your issue clearly).

From my review of the samples, I believe that you are hitting the issue that was addressed in issue #71 (which has since been `CLOSED` because we implemented the proposed change outlined there in `3.0-GA`).

If you wouldn't mind, could you review the content of #71 and let us know if you agree that its describing your use-case?  If so, then the answer (as outlined in that issue) is for your PCL classes that need a direct way to interact with `LogManager` to take a dependency on the `ILogManger` interface declared in the `Common.Logging.Core` assembly  rather than invoking `LogManager` directly.

For clarity, I've reworked your two test samples such that they (now) both run without any exceptions and attached them as [common.logging.tests-reworked.zip](https://github.com/net-commons/common-logging/files/1184347/common.logging.tests-reworked.zip).

This should be the same/similar structure as was used in the test branch referenced in #71 , still available for review at https://github.com/net-commons/common-logging/tree/pcl-experimentation/examples/PCLExample.

After you've reviewed #71 and my rework of your sample in detail (attached), let us know if that represents a viable mechanism to address your current issue.  If not, we'd be interested to understand the ways that this approach is a mismatch for your needs.

Thanks again for taking the time to craft these sample solutions, they were very helpful for clarifying your intent.

**Comment by braingame26** [comment] 2017-07-31 14:49
Thanks for the rework. I'll get back to you this afternoon (it's currently 9:50 AM here).

**Comment by braingame26** [comment] 2017-07-31 20:41
Thanks for taking the time to make the rework. So basically you have to pass the LogManager to the PCL, and the PCL just uses the ILogManager interface.

The product I'm developing is using a very large framework. The framework has specific ways I can add extensions to the framework, then it will dynamically load my extensions. So I'm not calling the constructors, so I can't pass in the LogManager.

The framework has it's own logging. What I ended up trying on Friday was creating my own implementation of the logging interface it uses. My implementation then calls common.logging. So the framework will load my logger, then my code (in the portable dlls) can calls it, then it calls common.logging. This is working :)

**Comment by sbohlen** [comment] 2017-08-01 22:24
@braingame26 great to hear that you have found _some_ mechanism that works for your use-case.

I'm honestly not sure that I completely understand how using your _own_ logger interface allows you to solve your issue any differently than taking a dependency on the `ILog` interface in `Common.Logging.Core` would.  But of course you know the specific details of your framework's strengths and weaknesses (and the hooks that permit you to satisfy its dependencies) much better than myself.  I'll certainly defer to your conclusion that implementing your own 'wrapper interface' around `Common.Logging` is a necessary (and viable) way to solve your issues.

As I said, happy that you managed to find a pattern than works for you.  I'll close this issue for now; feel free to re-open it and/or start a new one should anything (else) come up!

**Closed by sbohlen** 2017-08-01 22:24 UTC
Labels: bug
