### ISSUE TITLE
Dependency strictness of Common.Logging.Log4Net1213

### ISSUE THREAD

**Issue by DaveLaa** [net-commons/common-logging#152] opened 2017-09-20 07:00 UTC
In previous versions or Common.Logging.Log4Net1213 (V3.3.1) there was a Log4Net dependency "Log4Net >= 1.2.13". I saw the issue where you set this dependency to strict "Log4Net = 2.0.3". Is this important? I see no reason why we shouldn`t use the latest version of Log4Net like V2.0.8 for example. In the old version of Common.Logging.Log4Net1213 this worked perfectly and without any issues... Why do i now have to downgrade Log4Net or stay at my old version V3.3.1 of Common.Logging?
Isn`t it possible to make a more tollerant depenency like "Log4Net >= 2.0.3"?

**Comment by Gonnagle** [comment] 2017-09-20 07:42
This is probably duplicate of https://github.com/net-commons/common-logging/issues/140

We run into this exact same issue. I would have loved to see this changed to something like `Log4Net >= 2.0.3 < 3.0`, but unfortunately it seems there is [no guarantee that `Log4Net` follows SemVer](http://www.wiktorzychla.com/2012/03/pathetic-breaking-change-between.html) 😢

**Comment by DaveLaa** [comment] 2017-09-20 08:45
I`m using Common.Logging only as a bridge between Spring.Net and Log4Net and only for the Spring internal loggings. I Use Log4Net directly in the rest of my project, so i will prefere to upgrade Log4Net and freeze updates of Common.Logging in V3.3.1 where this issue was obviously not existing yet...

As long as there is no problem with compatigility in Log4Net, why creating problems in ALL projects that refere to Common.Logging worldwide? I must say that i disagree with this strictness caused by "possible problems in future". I would say that the Log4Net team did it correctly to inform all users of their braking change and that the Common.Logging team reacted correctly to create an extra library supporting these changes (Common.Logging.Log4Net1213). This could be done in future as well whenever there are breaking changes in Log4Net. And for now the dependency could be opened to >2.0.3

**Comment by DaveLaa** [comment] 2017-09-20 09:13
I just saw that there are now libraries for specific versions of Log4Net... I will install Common.Logging.Log4Net208 now.

**Closed** 2017-09-20 09:13 UTC
