### ISSUE TITLE
Could not install package 'Common.Logging.Portable 3.4.0-Alpha1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259'

### ISSUE THREAD

**Issue by haroldma** [net-commons/common-logging#126] opened 2016-07-14 02:52 UTC
But Core is supported.

**Comment by sbohlen** [comment] 2016-07-14 09:58
The `Alpha1` build was based on the pre-GA version of .NET Core, so my first guess is that this mismatch is probably the cause of the issue you're seeing here.

`MASTER` has already been updated to reflect the latest (GA) release of .NET Core and our hope is to be able to push an updated package (probably `Alpha2` or `Beta1`) to NuGet this coming weekend.  Once we do, I'll loop back here with a notice to that effect and I'd be interested in hearing whether that solved your issue (or whether there's something more significant going wrong with e.g. our NuGet packaging for this).

**Comment by sbohlen** [comment] 2016-10-02 19:31
Can you check whether the `Alpha2` release from last week solves this issue for you --?

**Comment by gjkhw** [comment] 2017-01-12 02:43
I have the same problem - the 3.4.0-Beta4 does not fix it, nor does Alpha2.  I see the same behavior on both Visual Studio 2015 Update 3 and on the latest Xamarin Studio Cycle 9 beta.

**Comment by sbohlen** [comment] 2017-02-11 15:37
We'll investigate this shortly; the plan is to resolve this before the 3.4 release goes GA.

**Comment by gjkhw** [comment] 2017-02-13 14:22
Thanks.  If you are able to resolve it, I would appreciate it.  I will circle back to it eventually if not, but my project has found some more pressing features that are keeping us on our workaround for now.

**Comment by sbohlen** [comment] 2017-07-26 18:10
Others have reported that this behavior has been corrected in our `3.4-RC1` packaging.  Can you confirm/validate this?  Our plans are to move 3.4 to GA by the end of this month and it would be helpful to know whether the `3.4-RC1` release has addressed your issues as well before we go to GA with it.

**Comment by gjkhw** [comment] 2017-07-26 18:12
I'll check it out ASAP.  Will aim for Friday or Monday at the latest. Thanks!

**Comment by sbohlen** [comment] 2017-07-26 18:14
@gjkhw Thanks -- that would be perfect.

Cheers!

**Comment by gjkhw** [comment] 2017-08-01 01:06
I can install this fine into PCL 259 and 111 projects. Unsurprisingly, code from Common.Logging.Portable runs just fine on Android and iOS devices. Thanks for sorting this out!

**Comment by sbohlen** [comment] 2017-08-01 13:42
Excellent -- will CLOSE this issue and prep for the launch of `3.4-GA` shortly.

**Closed by sbohlen** 2017-08-01 13:42 UTC
Labels: bug
